# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/loghin/CLionProjects/sesSI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/loghin/CLionProjects/sesSI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/loghin/CLionProjects/sesSI/CMakeFiles /home/loghin/CLionProjects/sesSI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/loghin/CLionProjects/sesSI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NodeKM

# Build rule for target.
NodeKM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NodeKM
.PHONY : NodeKM

# fast build rule for target.
NodeKM/fast:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/build
.PHONY : NodeKM/fast

#=============================================================================
# Target rules for targets named NodeB

# Build rule for target.
NodeB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NodeB
.PHONY : NodeB

# fast build rule for target.
NodeB/fast:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/build
.PHONY : NodeB/fast

#=============================================================================
# Target rules for targets named NodeA

# Build rule for target.
NodeA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NodeA
.PHONY : NodeA

# fast build rule for target.
NodeA/fast:
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/build
.PHONY : NodeA/fast

#=============================================================================
# Target rules for targets named CryptoManagerTest

# Build rule for target.
CryptoManagerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CryptoManagerTest
.PHONY : CryptoManagerTest

# fast build rule for target.
CryptoManagerTest/fast:
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/build
.PHONY : CryptoManagerTest/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/obj/KeyManager.o: src/obj/KeyManager.cpp.o

.PHONY : src/obj/KeyManager.o

# target to build an object file
src/obj/KeyManager.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/KeyManager.cpp.o
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/KeyManager.cpp.o
.PHONY : src/obj/KeyManager.cpp.o

src/obj/KeyManager.i: src/obj/KeyManager.cpp.i

.PHONY : src/obj/KeyManager.i

# target to preprocess a source file
src/obj/KeyManager.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/KeyManager.cpp.i
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/KeyManager.cpp.i
.PHONY : src/obj/KeyManager.cpp.i

src/obj/KeyManager.s: src/obj/KeyManager.cpp.s

.PHONY : src/obj/KeyManager.s

# target to generate assembly for a file
src/obj/KeyManager.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/KeyManager.cpp.s
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/KeyManager.cpp.s
.PHONY : src/obj/KeyManager.cpp.s

src/obj/NodeA.o: src/obj/NodeA.cpp.o

.PHONY : src/obj/NodeA.o

# target to build an object file
src/obj/NodeA.cpp.o:
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/NodeA.cpp.o
.PHONY : src/obj/NodeA.cpp.o

src/obj/NodeA.i: src/obj/NodeA.cpp.i

.PHONY : src/obj/NodeA.i

# target to preprocess a source file
src/obj/NodeA.cpp.i:
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/NodeA.cpp.i
.PHONY : src/obj/NodeA.cpp.i

src/obj/NodeA.s: src/obj/NodeA.cpp.s

.PHONY : src/obj/NodeA.s

# target to generate assembly for a file
src/obj/NodeA.cpp.s:
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/NodeA.cpp.s
.PHONY : src/obj/NodeA.cpp.s

src/obj/NodeB.o: src/obj/NodeB.cpp.o

.PHONY : src/obj/NodeB.o

# target to build an object file
src/obj/NodeB.cpp.o:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/NodeB.cpp.o
.PHONY : src/obj/NodeB.cpp.o

src/obj/NodeB.i: src/obj/NodeB.cpp.i

.PHONY : src/obj/NodeB.i

# target to preprocess a source file
src/obj/NodeB.cpp.i:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/NodeB.cpp.i
.PHONY : src/obj/NodeB.cpp.i

src/obj/NodeB.s: src/obj/NodeB.cpp.s

.PHONY : src/obj/NodeB.s

# target to generate assembly for a file
src/obj/NodeB.cpp.s:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/NodeB.cpp.s
.PHONY : src/obj/NodeB.cpp.s

src/obj/Server.o: src/obj/Server.cpp.o

.PHONY : src/obj/Server.o

# target to build an object file
src/obj/Server.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/Server.cpp.o
.PHONY : src/obj/Server.cpp.o

src/obj/Server.i: src/obj/Server.cpp.i

.PHONY : src/obj/Server.i

# target to preprocess a source file
src/obj/Server.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/Server.cpp.i
.PHONY : src/obj/Server.cpp.i

src/obj/Server.s: src/obj/Server.cpp.s

.PHONY : src/obj/Server.s

# target to generate assembly for a file
src/obj/Server.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/Server.cpp.s
.PHONY : src/obj/Server.cpp.s

src/obj/ServerThread.o: src/obj/ServerThread.cpp.o

.PHONY : src/obj/ServerThread.o

# target to build an object file
src/obj/ServerThread.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/ServerThread.cpp.o
.PHONY : src/obj/ServerThread.cpp.o

src/obj/ServerThread.i: src/obj/ServerThread.cpp.i

.PHONY : src/obj/ServerThread.i

# target to preprocess a source file
src/obj/ServerThread.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/ServerThread.cpp.i
.PHONY : src/obj/ServerThread.cpp.i

src/obj/ServerThread.s: src/obj/ServerThread.cpp.s

.PHONY : src/obj/ServerThread.s

# target to generate assembly for a file
src/obj/ServerThread.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/ServerThread.cpp.s
.PHONY : src/obj/ServerThread.cpp.s

src/obj/comm/ClientSocket.o: src/obj/comm/ClientSocket.cpp.o

.PHONY : src/obj/comm/ClientSocket.o

# target to build an object file
src/obj/comm/ClientSocket.cpp.o:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ClientSocket.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ClientSocket.cpp.o
.PHONY : src/obj/comm/ClientSocket.cpp.o

src/obj/comm/ClientSocket.i: src/obj/comm/ClientSocket.cpp.i

.PHONY : src/obj/comm/ClientSocket.i

# target to preprocess a source file
src/obj/comm/ClientSocket.cpp.i:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ClientSocket.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ClientSocket.cpp.i
.PHONY : src/obj/comm/ClientSocket.cpp.i

src/obj/comm/ClientSocket.s: src/obj/comm/ClientSocket.cpp.s

.PHONY : src/obj/comm/ClientSocket.s

# target to generate assembly for a file
src/obj/comm/ClientSocket.cpp.s:
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ClientSocket.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ClientSocket.cpp.s
.PHONY : src/obj/comm/ClientSocket.cpp.s

src/obj/comm/ServerSocket.o: src/obj/comm/ServerSocket.cpp.o

.PHONY : src/obj/comm/ServerSocket.o

# target to build an object file
src/obj/comm/ServerSocket.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/ServerSocket.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ServerSocket.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ServerSocket.cpp.o
.PHONY : src/obj/comm/ServerSocket.cpp.o

src/obj/comm/ServerSocket.i: src/obj/comm/ServerSocket.cpp.i

.PHONY : src/obj/comm/ServerSocket.i

# target to preprocess a source file
src/obj/comm/ServerSocket.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/ServerSocket.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ServerSocket.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ServerSocket.cpp.i
.PHONY : src/obj/comm/ServerSocket.cpp.i

src/obj/comm/ServerSocket.s: src/obj/comm/ServerSocket.cpp.s

.PHONY : src/obj/comm/ServerSocket.s

# target to generate assembly for a file
src/obj/comm/ServerSocket.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/ServerSocket.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/ServerSocket.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/ServerSocket.cpp.s
.PHONY : src/obj/comm/ServerSocket.cpp.s

src/obj/comm/Socket.o: src/obj/comm/Socket.cpp.o

.PHONY : src/obj/comm/Socket.o

# target to build an object file
src/obj/comm/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/Socket.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/Socket.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/Socket.cpp.o
.PHONY : src/obj/comm/Socket.cpp.o

src/obj/comm/Socket.i: src/obj/comm/Socket.cpp.i

.PHONY : src/obj/comm/Socket.i

# target to preprocess a source file
src/obj/comm/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/Socket.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/Socket.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/Socket.cpp.i
.PHONY : src/obj/comm/Socket.cpp.i

src/obj/comm/Socket.s: src/obj/comm/Socket.cpp.s

.PHONY : src/obj/comm/Socket.s

# target to generate assembly for a file
src/obj/comm/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/comm/Socket.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/comm/Socket.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/comm/Socket.cpp.s
.PHONY : src/obj/comm/Socket.cpp.s

src/obj/crypto/CryptoBlock.o: src/obj/crypto/CryptoBlock.cpp.o

.PHONY : src/obj/crypto/CryptoBlock.o

# target to build an object file
src/obj/crypto/CryptoBlock.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoBlock.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoBlock.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoBlock.cpp.o
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoBlock.cpp.o
.PHONY : src/obj/crypto/CryptoBlock.cpp.o

src/obj/crypto/CryptoBlock.i: src/obj/crypto/CryptoBlock.cpp.i

.PHONY : src/obj/crypto/CryptoBlock.i

# target to preprocess a source file
src/obj/crypto/CryptoBlock.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoBlock.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoBlock.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoBlock.cpp.i
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoBlock.cpp.i
.PHONY : src/obj/crypto/CryptoBlock.cpp.i

src/obj/crypto/CryptoBlock.s: src/obj/crypto/CryptoBlock.cpp.s

.PHONY : src/obj/crypto/CryptoBlock.s

# target to generate assembly for a file
src/obj/crypto/CryptoBlock.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoBlock.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoBlock.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoBlock.cpp.s
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoBlock.cpp.s
.PHONY : src/obj/crypto/CryptoBlock.cpp.s

src/obj/crypto/CryptoManager.o: src/obj/crypto/CryptoManager.cpp.o

.PHONY : src/obj/crypto/CryptoManager.o

# target to build an object file
src/obj/crypto/CryptoManager.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoManager.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoManager.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoManager.cpp.o
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoManager.cpp.o
.PHONY : src/obj/crypto/CryptoManager.cpp.o

src/obj/crypto/CryptoManager.i: src/obj/crypto/CryptoManager.cpp.i

.PHONY : src/obj/crypto/CryptoManager.i

# target to preprocess a source file
src/obj/crypto/CryptoManager.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoManager.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoManager.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoManager.cpp.i
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoManager.cpp.i
.PHONY : src/obj/crypto/CryptoManager.cpp.i

src/obj/crypto/CryptoManager.s: src/obj/crypto/CryptoManager.cpp.s

.PHONY : src/obj/crypto/CryptoManager.s

# target to generate assembly for a file
src/obj/crypto/CryptoManager.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoManager.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoManager.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoManager.cpp.s
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoManager.cpp.s
.PHONY : src/obj/crypto/CryptoManager.cpp.s

src/obj/crypto/CryptoObject.o: src/obj/crypto/CryptoObject.cpp.o

.PHONY : src/obj/crypto/CryptoObject.o

# target to build an object file
src/obj/crypto/CryptoObject.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoObject.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoObject.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoObject.cpp.o
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoObject.cpp.o
.PHONY : src/obj/crypto/CryptoObject.cpp.o

src/obj/crypto/CryptoObject.i: src/obj/crypto/CryptoObject.cpp.i

.PHONY : src/obj/crypto/CryptoObject.i

# target to preprocess a source file
src/obj/crypto/CryptoObject.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoObject.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoObject.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoObject.cpp.i
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoObject.cpp.i
.PHONY : src/obj/crypto/CryptoObject.cpp.i

src/obj/crypto/CryptoObject.s: src/obj/crypto/CryptoObject.cpp.s

.PHONY : src/obj/crypto/CryptoObject.s

# target to generate assembly for a file
src/obj/crypto/CryptoObject.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/CryptoObject.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/CryptoObject.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/CryptoObject.cpp.s
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/CryptoObject.cpp.s
.PHONY : src/obj/crypto/CryptoObject.cpp.s

src/obj/crypto/Key.o: src/obj/crypto/Key.cpp.o

.PHONY : src/obj/crypto/Key.o

# target to build an object file
src/obj/crypto/Key.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/Key.cpp.o
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/Key.cpp.o
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/Key.cpp.o
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/Key.cpp.o
.PHONY : src/obj/crypto/Key.cpp.o

src/obj/crypto/Key.i: src/obj/crypto/Key.cpp.i

.PHONY : src/obj/crypto/Key.i

# target to preprocess a source file
src/obj/crypto/Key.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/Key.cpp.i
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/Key.cpp.i
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/Key.cpp.i
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/Key.cpp.i
.PHONY : src/obj/crypto/Key.cpp.i

src/obj/crypto/Key.s: src/obj/crypto/Key.cpp.s

.PHONY : src/obj/crypto/Key.s

# target to generate assembly for a file
src/obj/crypto/Key.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/crypto/Key.cpp.s
	$(MAKE) -f CMakeFiles/NodeB.dir/build.make CMakeFiles/NodeB.dir/src/obj/crypto/Key.cpp.s
	$(MAKE) -f CMakeFiles/NodeA.dir/build.make CMakeFiles/NodeA.dir/src/obj/crypto/Key.cpp.s
	$(MAKE) -f CMakeFiles/CryptoManagerTest.dir/build.make CMakeFiles/CryptoManagerTest.dir/src/obj/crypto/Key.cpp.s
.PHONY : src/obj/crypto/Key.cpp.s

src/obj/thread/Semaphore.o: src/obj/thread/Semaphore.cpp.o

.PHONY : src/obj/thread/Semaphore.o

# target to build an object file
src/obj/thread/Semaphore.cpp.o:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/thread/Semaphore.cpp.o
.PHONY : src/obj/thread/Semaphore.cpp.o

src/obj/thread/Semaphore.i: src/obj/thread/Semaphore.cpp.i

.PHONY : src/obj/thread/Semaphore.i

# target to preprocess a source file
src/obj/thread/Semaphore.cpp.i:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/thread/Semaphore.cpp.i
.PHONY : src/obj/thread/Semaphore.cpp.i

src/obj/thread/Semaphore.s: src/obj/thread/Semaphore.cpp.s

.PHONY : src/obj/thread/Semaphore.s

# target to generate assembly for a file
src/obj/thread/Semaphore.cpp.s:
	$(MAKE) -f CMakeFiles/NodeKM.dir/build.make CMakeFiles/NodeKM.dir/src/obj/thread/Semaphore.cpp.s
.PHONY : src/obj/thread/Semaphore.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... NodeKM"
	@echo "... NodeB"
	@echo "... NodeA"
	@echo "... CryptoManagerTest"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/obj/KeyManager.o"
	@echo "... src/obj/KeyManager.i"
	@echo "... src/obj/KeyManager.s"
	@echo "... src/obj/NodeA.o"
	@echo "... src/obj/NodeA.i"
	@echo "... src/obj/NodeA.s"
	@echo "... src/obj/NodeB.o"
	@echo "... src/obj/NodeB.i"
	@echo "... src/obj/NodeB.s"
	@echo "... src/obj/Server.o"
	@echo "... src/obj/Server.i"
	@echo "... src/obj/Server.s"
	@echo "... src/obj/ServerThread.o"
	@echo "... src/obj/ServerThread.i"
	@echo "... src/obj/ServerThread.s"
	@echo "... src/obj/comm/ClientSocket.o"
	@echo "... src/obj/comm/ClientSocket.i"
	@echo "... src/obj/comm/ClientSocket.s"
	@echo "... src/obj/comm/ServerSocket.o"
	@echo "... src/obj/comm/ServerSocket.i"
	@echo "... src/obj/comm/ServerSocket.s"
	@echo "... src/obj/comm/Socket.o"
	@echo "... src/obj/comm/Socket.i"
	@echo "... src/obj/comm/Socket.s"
	@echo "... src/obj/crypto/CryptoBlock.o"
	@echo "... src/obj/crypto/CryptoBlock.i"
	@echo "... src/obj/crypto/CryptoBlock.s"
	@echo "... src/obj/crypto/CryptoManager.o"
	@echo "... src/obj/crypto/CryptoManager.i"
	@echo "... src/obj/crypto/CryptoManager.s"
	@echo "... src/obj/crypto/CryptoObject.o"
	@echo "... src/obj/crypto/CryptoObject.i"
	@echo "... src/obj/crypto/CryptoObject.s"
	@echo "... src/obj/crypto/Key.o"
	@echo "... src/obj/crypto/Key.i"
	@echo "... src/obj/crypto/Key.s"
	@echo "... src/obj/thread/Semaphore.o"
	@echo "... src/obj/thread/Semaphore.i"
	@echo "... src/obj/thread/Semaphore.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

